#!/usr/env ruby

tokens = []

f = File.open('tokens.y')

while not f.eof?
  line = f.readline
  line.chomp!.sub!(/^%token\s+/, '')
  tokens += line.split(' ')

end
f.close

f = $stdout; #File.open("mrTokens.h", 'w')

f.puts "// This file is automatically generated from tokens.y"
f.puts "// Using make_format_tokens."
f.puts

f.puts <<-TOKENLIST
enum mrTokenList \{ 
TOKENLIST

tokens.each { |t| 
    f.puts "TOK_#{t},"
}
f.puts "\};\n"

# f.puts <<-EOT
# struct mrToken
# {
#      char  value;
#      char* name;
# };
# EOT

f.puts "static const char* tokens[] = {"

tokens.each { |t|
  name = t.downcase.sub(/_/, ' ')
  f.puts "\"#{name}\","
}
f.puts "};"


f.close
